#!/bin/bash

MONGODB_URL=$MONGOLAB_URI
POSTGRESDB_URL=$DATABASE_URL

part1=${MONGODB_URL#mongodb://}
MONGODB_URL=${part1%:*}
echo $MONGODB_URL

part1=${MONGOLAB_URI#mongodb:*:*:}
MONGODB_PORT=${part1%/*}
MONGODB_DATABASE=${part1#*/}
echo $MONGODB_PORT
echo $MONGODB_DATABASE

part1=${DATABASE_URL#postgres://*@}
POSTGRESDB_URL=${part1%:*}
echo $POSTGRESDB_URL

part1=${DATABASE_URL#postgres:*:*:}
POSTGRESDB_DATABASE=${part1#*/}
echo $POSTGRESDB_DATABASE


export MONGODB_PORT MONGODB_DATABASE MONGODB_URL POSTGRESDB_URL POSTGRESDB_DATABASE